version: '2'
services:
 elastic-search:
  container_name: elasticsearch
  image: elasticsearch:latest
  ports:
  - "9200:9200"
  - "9300:9300"
  command: elasticsearch -Des.network.host=0.0.0.0
  volumes:
  - ./es-data:/usr/share/elasticsearch/data
 logstash:
  container_name: logstash
  image: logstash:latest
  volumes:
    - ./elk-config/logstash-data:/etc/logstash/conf.d
  ports:
    - "5000:5000"
  command: logstash -f /etc/logstash/conf.d/logstash.conf
  links:
    - elastic-search
 kibana:
  image: kibana:latest
  container_name: kibana
  volumes:
    - ./elk-config/kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elastic-search
